func Desencriptar()
dircreate(@tempDir &"\sounds")
FileInstall("sounds\alarm1.mp3", @TempDIR &"\sounds\alarm1.mp3")
FileInstall("sounds\alarm2.mp3", @TempDIR &"\sounds\alarm2.mp3")
FileInstall("sounds\alarm3.mp3", @TempDIR &"\sounds\alarm3.mp3")
FileInstall("sounds\alarm4.mp3", @TempDIR &"\sounds\alarm4.mp3")
FileInstall("sounds\bound.mp3", @TempDIR &"\sounds\bound.mp3")
FileInstall("sounds\close.mp3", @TempDIR &"\sounds\close.mp3")
FileInstall("sounds\CHECKBOX.mp3", @TempDIR &"\sounds\CHECKBOX.mp3")
FileInstall("sounds\CHECKBOX_unchecked.mp3", @TempDIR &"\sounds\CHECKBOX_unchecked.mp3")
FileInstall("sounds\error.mp3", @TempDIR &"\sounds\error.mp3")
FileInstall("sounds\open.mp3", @TempDIR &"\sounds\open.mp3")
FileInstall("sounds\ring1.mp3", @TempDIR &"\sounds\ring1.mp3")
FileInstall("sounds\ring2.mp3", @TempDIR &"\sounds\ring2.mp3")
FileInstall("sounds\ring3.mp3", @TempDIR &"\sounds\ring3.mp3")
FileInstall("sounds\ring4.mp3", @TempDIR &"\sounds\ring4.mp3")
FileInstall("sounds\ring5.mp3", @TempDIR &"\sounds\ring5.mp3")
FileInstall("sounds\ring6.mp3", @TempDIR &"\sounds\ring6.mp3")
FileInstall("sounds\ring7.mp3", @TempDIR &"\sounds\ring7.mp3")
FileInstall("sounds\ring8.mp3", @TempDIR &"\sounds\ring8.mp3")
FileInstall("sounds\ring9.mp3", @TempDIR &"\sounds\ring9.mp3")
FileInstall("sounds\ring10.mp3", @TempDIR &"\sounds\ring10.mp3")
FileInstall("sounds\radio.mp3", @TempDIR &"\sounds\radio.mp3")
FileInstall("sounds\scrollTop.mp3", @TempDIR &"\sounds\scrollTop.mp3")
FileInstall("sounds\selected.mp3", @TempDIR &"\sounds\selected.mp3")
FileInstall("sounds\soundlist.txt", @TempDIR &"\sounds\soundlist.txt")
EndFunc